import React, { createContext, useContext, useState, ReactNode, useCallback } from 'react';

export type Language = 'pt' | 'en';

export const translations = {
  tooltipDpc: { pt: 'Mede o tempo máximo gasto por drivers processando tarefas adiadas. Valores altos causam engasgos (stuttering) no sistema.', en: 'Measures the maximum time spent by drivers processing deferred tasks. High values cause system stuttering.' },
  tooltipIsr: { pt: 'Mede o tempo que o processador gasta lidando com interrupções de hardware (como mouse/teclado). Valores altos causam atrasos (input lag).', en: 'Measures the time the processor spends handling hardware interrupts (like mouse/keyboard). High values cause input lag.' },
  tooltipPagefaults: { pt: 'Ocorre quando o sistema precisa buscar no disco dados que deveriam estar na RAM. Quanto menor, mais rápido o sistema responde.', en: 'Occurs when the system has to fetch data from the disk that should be in the RAM. The lower, the faster the system responds.' },
  tooltipReliability: { pt: 'Indica a capacidade do sistema de lidar com áudio, vídeo e jogos sem engasgos, quedas de quadros ou desfoque de movimento.', en: 'Indicates the system\'s ability to handle audio, video, and gaming without stutters, dropped frames, or motion blur.' },
  energy: { pt: 'Energia', en: 'Power' },
  tooltipCpu: { pt: 'Unidade Central de Processamento. Mede o nível de atividade do processador principal.', en: 'Central Processing Unit. Measures the activity level of the main processor.' },
  tooltipGpu: { pt: 'Unidade de Processamento Gráfico. Mede o nível de atividade da placa de vídeo.', en: 'Graphics Processing Unit. Measures the activity level of the graphics card.' },
  tooltipRam: { pt: 'Memória de Acesso Aleatório. Mede a quantidade de memória volátil em uso.', en: 'Random Access Memory. Measures the amount of volatile memory in use.' },
  tooltipDisk: { pt: 'Mede a taxa de leitura e escrita do armazenamento (SSD/HDD).', en: 'Measures the read and write rate of the system storage (SSD/HDD).' },
  tooltipEnergy: { pt: 'Mede o consumo elétrico estimado do sistema em tempo real (Watts).', en: 'Measures the estimated electrical power consumption of the system in real-time (Watts).' },
  coreEngine: { pt: 'Motor Central', en: 'Core Engine' },
  theme: { pt: 'Tema', en: 'Theme' },
  dark: { pt: 'Escuro', en: 'Dark' },
  light: { pt: 'Claro', en: 'Light' },
  language: { pt: 'Idioma', en: 'Language' },
  systemSpecs: { pt: 'Especificações do PC', en: 'PC Specifications' },
  systemSpecsDesc: { pt: 'Visualização detalhada do hardware conectado.', en: 'Detailed view of connected hardware.' },
  processor: { pt: 'Processador (CPU)', en: 'Processor (CPU)' },
  lblModel: { pt: 'Modelo', en: 'Model' },
  lblCores: { pt: 'Núcleos/Threads', en: 'Cores/Threads' },
  lblBaseClock: { pt: 'Clock Base', en: 'Base Clock' },
  lblBoostClock: { pt: 'Clock Boost', en: 'Boost Clock' },
  lblCacheL3: { pt: 'Cache L3', en: 'L3 Cache' },
  lblVram: { pt: 'VRAM', en: 'VRAM' },
  lblDriver: { pt: 'Driver', en: 'Driver' },
  lblDirectx: { pt: 'DirectX', en: 'DirectX' },
  lblManufacturer: { pt: 'Fabricante', en: 'Manufacturer' },
  lblChipset: { pt: 'Chipset', en: 'Chipset' },
  lblBiosVersion: { pt: 'Versão da BIOS', en: 'BIOS Version' },
  lblTotalCapacity: { pt: 'Capacidade Total', en: 'Total Capacity' },
  lblSpeed: { pt: 'Velocidade', en: 'Speed' },
  lblType: { pt: 'Tipo', en: 'Type' },
  lblSlotsUsed: { pt: 'Slots Usados', en: 'Used Slots' },
  lblDisk1: { pt: 'Disco 1 (C:)', en: 'Disk 1 (C:)' },
  lblDisk2: { pt: 'Disco 2 (D:)', en: 'Disk 2 (D:)' },
  lblHealth: { pt: 'Saúde', en: 'Health' },
  lblHealthValue: { pt: 'Bom (100%)', en: 'Good (100%)' },
  lblPartitionType: { pt: 'Tipo de Partição', en: 'Partition Type' },
  lblEdition: { pt: 'Edição', en: 'Edition' },
  lblVersion: { pt: 'Versão', en: 'Version' },
  lblArchitecture: { pt: 'Arquitetura', en: 'Architecture' },
  lblSecureBoot: { pt: 'Boot Seguro', en: 'Secure Boot' },
  lblEnabled: { pt: 'Ativado', en: 'Enabled' },
  motherboard: { pt: 'Placa-mãe', en: 'Motherboard' },
  memory: { pt: 'Memória (RAM)', en: 'Memory (RAM)' },
  graphics: { pt: 'Placa de Vídeo (GPU)', en: 'Graphics (GPU)' },
  storage: { pt: 'Armazenamento', en: 'Storage' },
  os: { pt: 'Sistema Operacional', en: 'Operating System' },
  dashboard: { pt: 'Dashboard', en: 'Dashboard' },
  appsTab: { pt: 'Aplicativos', en: 'Apps' },
  appsDesc: { pt: 'Instale pacotes essenciais via PowerShell silenciosamente.', en: 'Install essential packages silently via PowerShell.' },
  catBrowsers: { pt: 'Navegadores', en: 'Browsers' },
  catGaming: { pt: 'Jogos', en: 'Gaming' },
  catComms: { pt: 'Comunicação', en: 'Communication' },
  catUtilities: { pt: 'Utilitários', en: 'Utilities' },
  install: { pt: 'Instalar', en: 'Install' },
  requested: { pt: 'Solicitado', en: 'Requested' },
  waitingData: { pt: 'Aguardando...', en: 'Waiting...' },
  scanningTitle: { pt: 'Inicializando Vantage OS', en: 'Initializing Vantage OS' },
  scanningDesc: { pt: 'Coletando informações do sistema...', en: 'Collecting system information...' },
  scanStep1: { pt: 'Analisando telemetria do processador...', en: 'Analyzing processor telemetry...' },
  scanStep2: { pt: 'Mapeando alocação de memória RAM...', en: 'Mapping RAM allocation...' },
  scanStep3: { pt: 'Verificando drives e partições...', en: 'Verifying drives and partitions...' },
  scanStep4: { pt: 'Carregando painel de controle...', en: 'Loading control panel...' },
  waitingBackendTitle: { pt: 'Aguardando conexão...', en: 'Waiting for connection...' },
  waitingBackendDesc: { pt: 'Aguardando dados do backend (localhost:3000)...', en: 'Waiting for backend data (localhost:3000)...' },
  profiles: { pt: 'Perfis de Uso', en: 'Usage Profiles' },
  custom: { pt: 'Customização', en: 'Customization' },
  support: { pt: 'Suporte', en: 'Support' },
  dashDesc: { pt: 'Visão geral do sistema e limpeza rápida.', en: 'System overview and quick cleaning.' },
  ramClean: { pt: 'Limpeza Rápida de RAM', en: 'Quick RAM Clean' },
  optimizing: { pt: 'Otimizando cache...', en: 'Optimizing cache...' },
  freed: { pt: 'Memória Liberada!', en: 'Memory Freed!' },
  optComplete: { pt: 'Otimização Concluída', en: 'Optimization Complete' },
  ramFreedMsg: { pt: 'de RAM liberados com sucesso.', en: 'of RAM successfully freed.' },
  sysUse: { pt: 'Uso do Sistema ao Vivo', en: 'Live System Usage' },
  latAnalysis: { pt: 'Análise de Latência do Sistema', en: 'System Latency Analysis' },
  latOpt: { pt: 'Seu sistema aparenta estar altamente otimizado para jogos e tarefas em tempo real sem interrupções de áudio ou quedas de FPS.', en: 'Your system appears highly optimized for gaming and real-time tasks with no audio dropouts or FPS drops.' },
  latWarn: { pt: 'O sistema está aceitável, mas as latências DPC podem sofrer picos ocasionais. Recomendado revisar perfis de energia.', en: 'System is acceptable, but DPC latencies may spike occasionally. Recommended to review power profiles.' },
  latDanger: { pt: 'Alta latência detectada. Altamente recomendado executar perfis de otimização gamer para evitar travamentos.', en: 'High latency detected. Highly recommended to run gamer optimization profiles to avoid stutters.' },
  reliability: { pt: 'Confiabilidade para Real-Time', en: 'Real-Time Reliability' },
  excellent: { pt: 'Excelente', en: 'Excellent' },
  profTitle: { pt: 'Perfis de Otimização', en: 'Optimization Profiles' },
  profDesc: { pt: 'Aplique configurações pré-definidas com um único clique.', en: 'Apply pre-defined configurations with a single click.' },
  profGamer: { pt: 'Modo Gamer', en: 'Gamer Mode' },
  profGamerDesc: { pt: 'Suspende automaticamente serviços de segundo plano não essenciais e ativa o plano de energia de alto desempenho para máxima fluidez.', en: 'Automatically suspends non-essential background services and activates the high-performance power plan for maximum fluidity.' },
  profCheck: { pt: 'Check-up & Limpeza', en: 'Check-up & Clean' },
  profCheckDesc: { pt: 'Reseta configurações para padrão de estabilidade, limpa caches profundos e remove telemetria para maior privacidade.', en: 'Resets settings to stability defaults, deeply cleans caches and removes telemetry for better privacy.' },
  applyProf: { pt: 'Aplicar Perfil', en: 'Apply Profile' },
  applying: { pt: 'Aplicando...', en: 'Applying...' },
  activeProf: { pt: 'Perfil Ativo', en: 'Active Profile' },
  modalProfDesc: { pt: 'Esta ação modificará configurações críticas de gerenciamento de energia, rede e serviços do Windows. Deseja prosseguir com a otimização?', en: 'This action will modify critical Windows power management, network, and services settings. Do you wish to proceed?' },
  confirmApply: { pt: 'Aplicar Otimizações', en: 'Apply Optimizations' },
  cancel: { pt: 'Cancelar', en: 'Cancel' },
  customTitle: { pt: 'Scripts Customizados', en: 'Custom Scripts' },
  customDesc: { pt: 'Selecione opções individuais para montar sua otimização ideal.', en: 'Select individual options to build your ideal optimization.' },
  applySelected: { pt: 'Aplicar Selecionados', en: 'Apply Selected' },
  executing: { pt: 'Executando...', en: 'Executing...' },
  applied: { pt: 'Aplicado!', en: 'Applied!' },
  catPerf: { pt: 'Desempenho', en: 'Performance' },
  catPriv: { pt: 'Privacidade', en: 'Privacy' },
  catNet: { pt: 'Rede', en: 'Network' },
  catSys: { pt: 'Sistema', en: 'System' },
  catUi: { pt: 'Interface', en: 'Interface' },
  optsAvail: { pt: 'opções disponíveis', en: 'options available' },
  toggleAll: { pt: 'Alternar Todos', en: 'Toggle All' },
  noOpt: { pt: 'Nenhuma otimização encontrada nesta categoria.', en: 'No optimizations found in this category.' },
  modalCustomTitle: { pt: 'Executar Scripts Customizados', en: 'Execute Custom Scripts' },
  modalCustomDescPre: { pt: 'Você está prestes a aplicar', en: 'You are about to apply' },
  modalCustomDescPost: { pt: 'script(s) de otimização. Alterações diretas no sistema operacional podem exigir a reinicialização para entrar em vigor. Tem certeza?', en: 'optimization script(s). Direct changes to the operating system may require a reboot to take effect. Are you sure?' },
  confirmExec: { pt: 'Confirmar Execução', en: 'Confirm Execution' },
  review: { pt: 'Revisar', en: 'Review' },
  fbTitle: { pt: 'Sobre & Suporte', en: 'About & Support' },
  fbDesc: { pt: 'Contribua com o projeto, relate bugs ou faça uma doação.', en: 'Contribute to the project, report bugs, or make a donation.' },
  supportDev: { pt: 'Apoie o Desenvolvimento', en: 'Support Development' },
  repo: { pt: 'Repositório GitHub', en: 'GitHub Repository' },
  repoDesc: { pt: 'Código fonte e documentação', en: 'Source code and documentation' },
  coffee: { pt: 'Compre me um café', en: 'Buy me a coffee' },
  coffeeDesc: { pt: 'Ajude a manter o servidor online', en: 'Help keep the server online' },
  madeWith: { pt: 'Criado com 🖤 pela comunidade.', en: 'Made with 🖤 by the community.' },
  npsTitle: { pt: 'Como você avalia nosso aplicativo?', en: 'How would you rate our app?' },
  npsDesc: { pt: 'Sua opinião nos ajuda a melhorar.', en: 'Your opinion helps us improve.' },
  npsCommentPlaceholder: { pt: 'Deixe um comentário opcional...', en: 'Leave an optional comment...' },
  npsSubmit: { pt: 'Enviar Avaliação', en: 'Submit Rating' },
  npsSuccess: { pt: 'Obrigado pelo seu feedback!', en: 'Thank you for your feedback!' },
  sendFb: { pt: 'Enviar Feedback', en: 'Send Feedback' },
  fbLabel: { pt: 'Encontrou um bug ou tem uma sugestão?', en: 'Found a bug or have a suggestion?' },
  fbPlaceholder: { pt: 'Descreva aqui sua experiência ou sugestão...', en: 'Describe your experience or suggestion here...' },
  sendMsg: { pt: 'Enviar Mensagem', en: 'Send Message' },
  fbSent: { pt: 'Feedback Enviado! Obrigado.', en: 'Feedback Sent! Thank you.' },
  githubProj: { pt: 'GitHub do Projeto', en: 'Project GitHub' },
  supportProj: { pt: 'Apoiar Projeto', en: 'Support Project' },
  netToolsTitle: { pt: 'Diagnóstico e Ferramentas de Rede', en: 'Network Diagnostics & Tools' },
  pingLabel: { pt: 'Latência Atual (8.8.8.8)', en: 'Current Latency (8.8.8.8)' },
  statusOnline: { pt: 'Conexão Estável', en: 'Stable Connection' },
  dnsLabel: { pt: 'Servidor DNS Preferencial', en: 'Preferred DNS Server' },
  dnsAuto: { pt: 'Automático (Padrão)', en: 'Automatic (Default)' },
  apply: { pt: 'Aplicar', en: 'Apply' },
  netResetTitle: { pt: 'Redefinição Profunda', en: 'Deep Reset' },
  netResetDesc: { pt: 'Limpa o cache DNS, renova o IP e reseta os catálogos Winsock.', en: 'Clears DNS cache, renews IP, and resets Winsock catalogs.' },
  runReset: { pt: 'Resetar Rede', en: 'Reset Network' },
  modalNetTitle: { pt: 'Redefinir Adaptadores de Rede', en: 'Reset Network Adapters' },
  modalNetDesc: { pt: 'Sua conexão com a internet cairá por alguns segundos enquanto o adaptador é reiniciado. Deseja prosseguir?', en: 'Your internet connection will drop for a few seconds while the adapter restarts. Proceed?' },
  networkTab: { pt: 'Rede & DNS', en: 'Network & DNS' },
  networkDesc: { pt: 'Analise sua latência, altere o DNS e redefina adaptadores.', en: 'Analyze your latency, change DNS and reset adapters.' },
  latencyMonitorTitle: { pt: 'Monitor de Latência', en: 'Latency Monitor' },
  latencyMonitorDesc: { pt: 'Análise de estabilidade da conexão em tempo real', en: 'Real-time connection stability analysis' },
  pingTestTitle: { pt: "Teste de Roteamento & Latência", en: "Routing & Latency Test" },
  pingTestDesc: { pt: "Analisa a latência, perda de pacotes e picos de jitter para os principais servidores.", en: "Analyzes latency, packet loss, and jitter spikes to major servers." },
  runPingTest: { pt: "Iniciar Teste de Ping", en: "Run Ping Test" },
  pinging: { pt: "Testando...", en: "Testing..." },
  latency: { pt: "Latência", en: "Latency" },
  jitter: { pt: "Jitter", en: "Jitter" },
  packetLoss: { pt: "Queda de Pacotes", en: "Packet Loss" },
  spikes: { pt: "Picos Repentinos", en: "Sudden Spikes" },
  detected: { pt: "Detectado", en: "Detected" },
  none: { pt: "Nenhum", en: "None" },
  endpoint: { pt: 'Servidor', en: 'Endpoint' },
  avgPing: { pt: 'Média (ms)', en: 'Avg (ms)' },
  stability: { pt: 'Estabilidade', en: 'Stability' },
  viewCustomize: { pt: 'Visualizar & Customizar', en: 'View & Customize' },
  saveProfile: { pt: 'Salvar Perfil', en: 'Save Profile' },
  savedSuccess: { pt: 'Perfil Salvo!', en: 'Profile Saved!' },
  myProfile: { pt: 'Meu Perfil Pessoal', en: 'My Personal Profile' },
  myProfileDesc: { pt: 'Sua seleção customizada de otimizações, salva para acesso rápido.', en: 'Your custom selection of optimizations, saved for quick access.' },
  emptyProfile: { pt: 'Nenhum script salvo', en: 'No scripts saved' },
  renameProfile: { pt: 'Renomear Perfil', en: 'Rename Profile' },
  historyTitle: { pt: 'Histórico de Execução', en: 'Execution History' },
  historyDesc: { pt: 'Últimas otimizações aplicadas e seus status.', en: 'Latest applied optimizations and their status.' },
  statusSuccess: { pt: 'Sucesso', en: 'Success' },
  statusError: { pt: 'Erro', en: 'Error' },
  emptyHistory: { pt: 'Nenhum histórico disponível.', en: 'No history available yet.' },
  createRestorePoint: { pt: 'Criar Ponto de Restauração', en: 'Create Restore Point' },
  restorePointDesc: { pt: 'Garante segurança permitindo reverter as alterações caso algo não funcione bem.', en: 'Ensures safety by allowing you to revert changes if something goes wrong.' },
  undoAll: { pt: 'Desfazer Tudo', en: 'Undo All' },
  undoing: { pt: 'Desfazendo...', en: 'Undoing...' },
  undoSuccess: { pt: 'Mudanças revertidas com sucesso!', en: 'Changes successfully reverted!' },
  junkFilesTitle: { pt: 'Limpeza de Disco', en: 'Disk Cleanup' },
  junkFilesDesc: { pt: 'Arquivos temporários e cache do sistema', en: 'Temporary files and system cache' },
  tempFiles: { pt: 'Arquivos Temporários', en: 'Temp Files' },
  freeSpace: { pt: 'Espaço Livre', en: 'Free Space' },
  cleanJunk: { pt: 'Limpar Lixo', en: 'Clean Junk' },
  cleaningJunk: { pt: 'Limpando...', en: 'Cleaning...' },
  junkCleaned: { pt: 'Limpo!', en: 'Cleaned!' },
  ramTitle: { pt: 'Otimização de RAM', en: 'RAM Optimization' },
  ramDesc: { pt: 'Libera memória em cache e processos suspensos', en: 'Frees cached memory and suspended processes' },
  ramUsed: { pt: 'Em Uso', en: 'In Use' },
  ramAvailable: { pt: 'Disponível', en: 'Available' },
  optimize: { pt: 'Otimizar', en: 'Optimize' },
  optimizingRam: { pt: 'Otimizando...', en: 'Optimizing...' },
  optimized: { pt: 'Otimizado!', en: 'Optimized!' },
  checkUpdates: { pt: 'Verificar Atualizações', en: 'Check for Updates' },
  checkingUpdates: { pt: 'Verificando...', en: 'Checking...' },
  installingUpdate: { pt: 'Instalando...', en: 'Installing...' },
  updated: { pt: 'Atualizado!', en: 'Updated!' },
  exportLogs: { pt: 'Exportar Histórico', en: 'Export History' },
  undoLastAction: { pt: 'Desfazer Última Ação', en: 'Undo Last Action' },
  undoBtn: { pt: 'Desfazer', en: 'Undo' },
  undoingAction: { pt: 'Desfazendo...', en: 'Undoing...' },
  tourWelcomeTitle: { pt: 'Bem-vindo ao Vantage OS', en: 'Welcome to Vantage OS' },
  tourWelcomeDesc: { pt: 'Vamos fazer um tour rápido para conhecer as principais ferramentas que vão turbinar o seu sistema.', en: "Let's take a quick tour to discover the main tools that will boost your system." },
  tourDashboardTitle: { pt: 'Dashboard Inteligente', en: 'Smart Dashboard' },
  tourDashboardDesc: { pt: 'Monitore o uso do hardware em tempo real, limpe arquivos inúteis e otimize sua memória RAM com um único clique.', en: 'Monitor hardware usage in real-time, clean junk files, and optimize your RAM with a single click.' },
  tourProfilesTitle: { pt: 'Perfis de Otimização', en: 'Optimization Profiles' },
  tourProfilesDesc: { pt: 'Aplique dezenas de configurações automaticamente escolhendo o perfil ideal para o seu uso (Gamer, Criador, Minimalista).', en: 'Apply dozens of settings automatically by choosing the ideal profile for your use case (Gamer, Creator, Minimalist).' },
  tourCustomTitle: { pt: 'Ajustes Customizados', en: 'Custom Tweaks' },
  tourCustomDesc: { pt: 'Tenha controle granular. Ative ou desative recursos específicos do Windows com total segurança e pontos de restauração.', en: 'Have granular control. Enable or disable specific Windows features with total security and restore points.' },
  tourSkip: { pt: 'Pular Tour', en: 'Skip Tour' },
  tourNext: { pt: 'Próximo', en: 'Next' },
  tourPrev: { pt: 'Anterior', en: 'Previous' },
  tourStart: { pt: 'Começar!', en: 'Get Started!' },
  undoAllBat: { pt: 'undo_all.bat (Reverter para Padrão)', en: 'undo_all.bat (Revert to Default)' },
};

const LanguageContext = createContext<{
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: keyof typeof translations) => string;
}>({
  lang: 'pt',
  setLang: () => {},
  t: (key) => key as string,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>('pt');
  const t = useCallback((key: keyof typeof translations) => translations[key]?.[lang] || key, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
